# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: edu-ricardo
email: 1edu.ricardo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portifolio de aplicações (sites, app, softwares) criados por Eduardo Ricardo
  e hospedados no github.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://edu-ricardo.github.io" # the base hostname & protocol for your site
twitter_username: edu_ricardo
github_username:  edu-ricardo
author: Eduardo Ricardo
# Build settings
markdown: kramdown
collections:
projects:
output: true